# --- 1) Install deps with Node 20
FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
# Install without running postinstall (we call prisma generate ourselves later)
RUN if [ -f package-lock.json ]; then npm ci --ignore-scripts; else npm i --ignore-scripts; fi

# --- 2) Build
FROM node:20-alpine AS builder
WORKDIR /app

# Copy installed node_modules from deps
COPY --from=deps /app/node_modules ./node_modules
# Copy the rest of the repo
COPY . .

ENV NEXT_TELEMETRY_DISABLED=1
# Generate Prisma client explicitly (no DB connection required)
RUN npx prisma generate
# Build Next with standalone output (your next.config.js already sets output: 'standalone')
RUN npm run build

# --- 3) Run minimal image
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
# Copy the standalone server bundle
COPY --from=builder /app/.next/standalone ./
# Static assets
COPY --from=builder /app/.next/static ./.next/static
# Public assets (if any)
COPY --from=builder /app/public ./public

EXPOSE 3000
# server.js is generated by Next in the standalone bundle
CMD ["node", "server.js"]
