import React from "react";
import Link from "next/link";

const EFFECTIVE_DATE = "September 13, 2025";
const LAST_UPDATED = "September 13, 2025";

export const metadata = {
  title: "Privacy Policy | linkmint.co",
  description:
    "How linkmint.co collects, uses, and protects your data, including account info, analytics, and payout details.",
};

export default function PrivacyPage() {
  return (
    <main className="min-h-screen px-4 py-10 md:py-16">
      <div className="mx-auto w-full max-w-3xl">
        <header className="mb-8">
          <h1 className="text-3xl font-bold tracking-tight">Privacy Policy</h1>
          <p className="mt-2 text-sm text-gray-600">
            <span className="mr-3">Effective:</span>
            <time dateTime="2025-09-13">{EFFECTIVE_DATE}</time>
            <span className="mx-3">•</span>
            <span>
              Last Updated: <time dateTime="2025-09-13">{LAST_UPDATED}</time>
            </span>
          </p>
          <p className="mt-3 text-sm text-gray-600">
            This Privacy Policy explains how <strong>linkmint.co</strong> (“Linkmint,” “we,”
            “us,” or “our”) collects, uses, and shares information about you when you use our
            website and services (the “Services”).
          </p>
        </header>

        <section className="prose prose-gray max-w-none">
          <h2>1. Information We Collect</h2>
          <ul>
            <li>
              <strong>Account Information:</strong> name, email, password (hashed), age
              confirmation, TOS acceptance timestamp/IP, referral details, TrustScore,
              verification tokens.
            </li>
            <li>
              <strong>Usage & Device Data:</strong> IP address, browser/user agent, pages
              viewed, timestamps, and interactions; cookie identifiers and similar technologies.
            </li>
            <li>
              <strong>Affiliate & Earnings Data:</strong> clicks, conversions, merchant/network
              approvals, commission statuses (pending/approved/paid), payout logs.
            </li>
            <li>
              <strong>Payment & Payout Data:</strong> PayPal account email (for payouts),
              payout amounts, fees. We do <em>not</em> store full bank card numbers.
            </li>
            <li>
              <strong>Communications:</strong> emails and messages you send to support; event
              logs generated by the system (e.g., signup, verification, payouts).
            </li>
          </ul>

          <h2>2. How We Use Information</h2>
          <ul>
            <li>Provide, operate, and improve the Services.</li>
            <li>Authenticate users, prevent fraud/abuse, and protect platform integrity.</li>
            <li>Track referrals, clicks, commissions, approvals, and payouts.</li>
            <li>Send service emails (verification, receipts, alerts, policy updates).</li>
            <li>Comply with legal obligations and enforce our Terms of Service.</li>
            <li>Analyze aggregate usage to enhance reliability and performance.</li>
          </ul>

          <h2>3. Cookies & Similar Technologies</h2>
          <p>
            We use cookies and similar technologies to keep you signed in, remember preferences,
            and measure performance. You can control cookies in your browser settings, but some
            features may not work correctly without them.
          </p>

          <h2>4. Sharing of Information</h2>
          <ul>
            <li>
              <strong>Service Providers:</strong> trusted vendors that help us run the Services
              (e.g., email delivery, hosting, analytics, error monitoring).
            </li>
            <li>
              <strong>Affiliate Networks/Merchants:</strong> to validate conversions and
              compute commissions consistent with their terms.
            </li>
            <li>
              <strong>Compliance & Safety:</strong> to comply with laws, respond to lawful
              requests, and protect rights, property, and users.
            </li>
            <li>
              <strong>Business Transfers:</strong> in a merger, acquisition, or asset sale,
              information may be transferred as permitted by law.
            </li>
          </ul>

          <h2>5. Data Retention</h2>
          <p>
            We retain information for as long as necessary to provide the Services, meet legal,
            tax, and accounting obligations, resolve disputes, and enforce agreements. Retention
            periods vary by data type and legal requirements.
          </p>

          <h2>6. Security</h2>
          <p>
            We employ administrative, technical, and physical safeguards designed to protect your
            information. No method of transmission or storage is 100% secure, and we cannot
            guarantee absolute security.
          </p>

          <h2>7. Your Choices & Rights</h2>
          <ul>
            <li>
              <strong>Account:</strong> You can update certain profile details or request
              deletion of your account, subject to our fraud-prevention and recordkeeping needs.
            </li>
            <li>
              <strong>Emails:</strong> You may opt out of non-essential emails; service
              messages (e.g., verification, policy changes) are required.
            </li>
            <li>
              <strong>Cookies:</strong> Browser tools can limit cookies; essential cookies are
              required for core functionality.
            </li>
          </ul>

          <h2>8. Children’s Privacy</h2>
          <p>
            The Services are not directed to children under 18. We do not knowingly collect
            personal information from children under 18.
          </p>

          <h2>9. International Users</h2>
          <p>
            Our Services are operated in the United States. If you access the Services from
            outside the U.S., you consent to the transfer, processing, and storage of your
            information in the U.S.
          </p>

          <h2>10. Changes to This Policy</h2>
          <p>
            We may update this Privacy Policy from time to time. Material updates will be
            communicated via the dashboard or email. The “Last Updated” date reflects the latest
            changes.
          </p>

          <h2>11. Contact Us</h2>
          <p>
            Questions? Contact{" "}
            <a className="text-blue-600 hover:underline" href="mailto:admin@linkmint.co">
              admin@linkmint.co
            </a>
            .
          </p>

          <hr className="my-10" />

          <p className="text-xs text-gray-600">
            By using the Services, you agree to this Privacy Policy and our{" "}
            <Link className="text-blue-600 hover:underline" href="/terms">
              Terms of Service
            </Link>
            .
          </p>
        </section>
      </div>
    </main>
  );
}
