name: E2E (Playwright)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install deps
        run: npm ci

      - name: Install Playwright (with browsers)
        run: npx playwright install --with-deps

      - name: Run tests
        env:
          E2E_BASE_URL: https://linkmint.co
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASS: ${{ secrets.ADMIN_PASS }}
        run: npx playwright test
