name: Verify

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Verify Prisma + TypeScript
        run: npm run verify

      - name: Start Next.js server
        run: npm run build && npm run start &

      - name: Wait for server
        run: npx wait-on http://localhost:3000

      - name: Run Playwright API health tests
        run: npx playwright test -c playwright.api.config.ts
